<a href="https://colab.research.google.com/github/MissMakara/Transform-Learning/blob/main/transform_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import train_test_split
import numpy as np 
from  matplotlib import pyplot as plt
import matplotlib.image as mpimg
%matplotlib inline
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import joblib
import tensorflow as tf
from tensorflow import keras
from skimage.io import imread
from skimage.transform import resize
from sklearn import svm
import imutils
from imutils import paths

import cv2
import os

In [ ]:
def image_dataset(eye_dataset):
    
    IMG_WIDTH=224
    IMG_HEIGHT=224
    img_data_array=[]
    class_name=[]
    nd_image_array=[]
   
    for folder in os.listdir(eye_dataset):
        for file in os.listdir(os.path.join(eye_dataset,folder)):

          image_path= os.path.join(eye_dataset,folder,file)
          #image=mpimg.imread(image_path)
          image= cv2.imread(image_path,cv2.IMREAD_COLOR)

          #change image to np array and print shape
          image = np.array(image)
          
          
          #assign the dimensions
          try:
            ht =image.shape[0]
            wd =image.shape[1]
            cc =image.shape[2] 
            #print(image.shape)

          # create new image of desired size and color (blue) for padding
          #  ww = 300
          #  hh = 300
          #  color = (255,0,0)
          #  result = np.full((hh,ww,cc), color, dtype=np.uint8)

          #  xx = (ww - wd) // 2
         #   yy = (hh - ht) // 2


            # copy img image into center of result image
           # image = result[yy:yy+ht, xx:xx+wd]
          
            top_pad = np.floor((ht - image.shape[0]) / 2).astype(np.uint16)
            bottom_pad = np.ceil((ht - image.shape[0]) / 2).astype(np.uint16)
            right_pad = np.ceil((wd - image.shape[1]) / 2).astype(np.uint16)
            left_pad = np.floor((wd - image.shape[1]) / 2).astype(np.uint16)
            image = np.copy(np.pad(image, ((top_pad, bottom_pad), (left_pad, right_pad), (0, 0)), mode='constant', constant_values=0))

            ht =0
            wd =0
            cc =0

            try:
                image =cv2.resize(image,(IMG_HEIGHT, IMG_WIDTH))
            except Exception as e:
                print(str(e))

            image=np.array(image)
            flat_image= image.flatten()
            image = image.astype('float32')
            #image /= 255 
            
            
            class_name.append(folder)
            img_data_array.append(flat_image)
            nd_image_array.append(image)
            
          except Exception as e:
            print(str(e))
            ax=plt.subplot(1,5,i+1)
            ax.title.set_text(file)
            plt.imshow(image)

    #img_data_array = np.array(img_data_array)
    #class_name = np.array(class_name)
    return img_data_array, class_name, nd_image_array

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
img_data_, class_names_, nd_array = image_dataset(r'/content/drive/MyDrive/Docsun Health/Eyes Dataset/Edited Dataset/')

In [ ]:
nd_array = np.array(nd_array)

In [ ]:
img_data = np.array(img_data_)
class_names = np.array(class_names_)

In [ ]:
nd_array.shape

(557, 224, 224, 3)

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
target = le.fit_transform(class_names)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
img_data_=scaler.fit_transform(img_data)

In [ ]:
target.shape

(557,)

In [ ]:
img_data.shape

(557, 150528)

In [ ]:
X = img_data_
y = target


In [ ]:
from sklearn.utils import shuffle
X_shuffled,y_shuffled = shuffle(X, y, random_state=32)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_shuffled, y_shuffled, test_size=0.30, random_state=30)

In [ ]:
X_test.shape

(168, 150528)

In [ ]:

# define support vector classifier
svm_model = svm.SVC(kernel='rbf', probability=True, random_state=42, gamma='auto', max_iter = 200)

# fit model


In [ ]:
svm_model.fit(X_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:231: ConvergenceWarning: Solver terminated early (max_iter=200).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  % self.max_iter, ConvergenceWarning)


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=200, probability=True, random_state=42, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
svm_predicted_y = svm_model.predict(X_test)


In [ ]:
svm_predicted_y

array([1, 2, 2, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 2, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 2, 2, 0, 1, 0, 0, 1, 1, 2, 1, 1, 0, 1, 2, 1, 1, 1, 0, 2, 1,
       1, 1, 0, 2, 0, 0, 2, 0, 1, 0, 1, 1, 0, 2, 2, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 2, 2, 1, 2, 1, 0,
       1, 0, 2, 1, 2, 1, 0, 0, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 0, 0, 1, 2,
       0, 1, 1, 1, 0, 0, 0, 2, 1, 0, 1, 2, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0,
       1, 0, 0, 1, 0, 1, 1, 2, 2, 0, 1, 1, 1, 1])

In [ ]:
from sklearn import metrics
meanAbsError = metrics.mean_absolute_error(np.array(y_test), svm_predicted_y)
meanSqrdError = metrics.mean_squared_error(np.array(y_test), svm_predicted_y)
rootMeanSqrdError = np.sqrt(meanSqrdError)

print("Mean Absolute Error", meanAbsError)
print("Mean Squared Error", meanSqrdError)
print("Root Mean Squared error", rootMeanSqrdError)


Mean Absolute Error 0.26785714285714285
Mean Squared Error 0.4107142857142857
Root Mean Squared error 0.6408699444616557


In [ ]:
print(" SVM Classification Report: \n{}\n".format(metrics.classification_report(y_test, svm_predicted_y, target_names=['0','1','2'], zero_division = 1)))

 SVM Classification Report: 
              precision    recall  f1-score   support

           0       0.75      0.91      0.82        56
           1       0.84      0.87      0.85        70
           2       0.85      0.55      0.67        42

    accuracy                           0.80       168
   macro avg       0.81      0.78      0.78       168
weighted avg       0.81      0.80      0.80       168




In [ ]:
print(" SVM Classification Report: \n{}\n".format(metrics.classification_report(y_test, svm_predicted_y, target_names=['0','1','2'], zero_division = 1)))

 SVM Classification Report: 
              precision    recall  f1-score   support

           0       1.00      0.00      0.00        56
           1       0.42      1.00      0.59        70
           2       1.00      0.00      0.00        42

    accuracy                           0.42       168
   macro avg       0.81      0.33      0.20       168
weighted avg       0.76      0.42      0.25       168




In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy on SVM Model: ",accuracy_score(y_test,svm_predicted_y))

Accuracy on SVM Model:  0.8035714285714286


In [ ]:
#knn = OneVsRestClassifier(KNeighborsClassifier())
knn = KNeighborsClassifier(n_neighbors=10)

In [ ]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [ ]:
knn_predicted = knn.predict(X_test)

In [ ]:
knn_predicted

array([1, 2, 0, 0, 1, 0, 0, 2, 1, 1, 1, 1, 1, 2, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 2, 0, 1, 0, 0, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 0, 2, 1,
       1, 1, 0, 0, 1, 1, 2, 0, 1, 0, 1, 1, 0, 2, 2, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 2, 2, 1, 2, 1, 0,
       1, 0, 2, 1, 2, 1, 0, 0, 0, 1, 1, 1, 1, 2, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 2, 1, 0, 1, 2, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 1, 2, 0, 0, 2, 0, 0, 0, 1, 0, 2, 0,
       1, 0, 0, 1, 0, 0, 1, 2, 2, 0, 1, 1, 1, 1])

In [ ]:
meanAbsError = metrics.mean_absolute_error(np.array(y_test), knn_predicted)
meanSqrdError = metrics.mean_squared_error(np.array(y_test), knn_predicted)
rootMeanSqrdError = np.sqrt(meanSqrdError)
print("KNN Metrics")
print("Mean Absolute Error", meanAbsError)
print("Mean Squared Error", meanSqrdError)
print("Root Mean Squared error", rootMeanSqrdError)

KNN Metrics
Mean Absolute Error 0.34523809523809523
Mean Squared Error 0.5357142857142857
Root Mean Squared error 0.7319250547113999


In [ ]:
print(" KNN Classification Report: \n{}\n".format(metrics.classification_report(y_test, knn_predicted, target_names=['0','1','2'], zero_division = 1)))

 KNN Classification Report: 
              precision    recall  f1-score   support

           0       0.70      0.82      0.75        56
           1       0.79      0.86      0.82        70
           2       0.77      0.48      0.59        42

    accuracy                           0.75       168
   macro avg       0.75      0.72      0.72       168
weighted avg       0.75      0.75      0.74       168




In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy of KNN model:",accuracy_score(y_test,knn_predicted))

Accuracy of KNN model: 0.75


In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
lr_predicted = lr.predict(X_test)


In [ ]:
lr_predicted

array([ 0.83084029,  2.04455874,  2.29165829, -0.15101669,  1.14500918,
       -0.11860905, -1.47533729,  1.51618565,  0.52054478,  1.04876285,
        0.53929794,  0.56477133,  0.65188344,  1.94855053,  0.6286338 ,
       -0.23444181,  0.70404116,  1.43064113,  0.77468174,  0.99379447,
        1.26918416,  0.3065636 ,  1.5909351 ,  1.13969552,  1.7474034 ,
        1.3256329 , -0.06004953,  1.61918543,  1.72179103,  0.28016398,
        0.76389278,  0.39094812,  2.70583045,  0.87218265,  1.7826198 ,
        0.2194988 ,  1.04315225,  1.83597562,  0.48993993,  1.3299653 ,
        0.53050576,  0.41671864,  2.13900008,  0.97327931,  1.16008844,
        1.48019378,  0.10552228,  1.53820821,  0.98351418, -0.64497873,
        1.95643721,  1.34994466,  0.72250509,  0.6339947 ,  0.62981965,
        0.59857632,  1.99942202,  1.93381667,  1.7395923 , -0.18547886,
        0.07010933,  1.46376149,  0.25741986,  1.261686  ,  0.3162168 ,
        0.96767108,  0.81272723,  0.35702998,  0.62523515,  0.80

In [ ]:
meanAbsError = metrics.mean_absolute_error(np.array(y_test), lr_predicted)
meanSqrdError = metrics.mean_squared_error(np.array(y_test), lr_predicted)
rootMeanSqrdError = np.sqrt(meanSqrdError)
print("Linear Regression Metrics")
print("Mean Absolute Error", meanAbsError)
print("Mean Squared Error", meanSqrdError)
print("Root Mean Squared error", rootMeanSqrdError)

Linear Regression Metrics
Mean Absolute Error 0.36040663800534434
Mean Squared Error 0.21936065519113465
Root Mean Squared error 0.46835953624446963


In [ ]:
#cnn model creation
cnn_model = keras.Sequential([
    keras.layers.Conv2D(8,(3,3), activation = 'relu',input_shape = (32,32,3)),

    keras.layers.Conv2D(16, (3,3), activation = 'relu'),
    #keras.layers.MaxPooling2D(2,2),

    keras.layers.Conv2D(32,(3,3),activation = 'relu'),
    #keras.layers.MaxPooling2D(2,2),

    keras.layers.Flatten(),
    keras.layers.Dense(32, activation = 'relu'),
    keras.layers.Dropout(0.25),
    keras.layers.Dense(1, activation = 'relu')

])

In [ ]:
X_ = nd_array
y_ = target

In [ ]:
#y_array =np.array(y_)

In [ ]:
y_

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [ ]:
X_.shape

(557, 224, 224, 3)

In [ ]:
from keras.utils import np_utils
y_cat = np_utils.to_categorical(target, 1000)

In [ ]:
y_cat.shape

(557, 1000)

In [ ]:
X_train_, X_test_, y_train_, y_test_ = train_test_split(X_, y_cat, test_size=0.30, random_state=30)

In [ ]:
X_train_.shape

(389, 224, 224, 3)

In [ ]:
cnn_model.compile(loss='binary_crossentropy',
              optimizer= keras.optimizers.SGD(learning_rate=0.01, momentum=0.9),
              metrics=['accuracy'])

In [ ]:
cnn_model.fit(X_train_, y_train_, batch_size=64, epochs=10, validation_data=(X_test_, y_test_))

Epoch 1/10
7/7 [==============================] - 1s 103ms/step - loss: 13.0066 - accuracy: 0.3753 - val_loss: 13.6805 - val_accuracy: 0.3095
Epoch 2/10
7/7 [==============================] - 1s 99ms/step - loss: 13.2044 - accuracy: 0.3779 - val_loss: 13.6805 - val_accuracy: 0.3095
Epoch 3/10
7/7 [==============================] - 1s 100ms/step - loss: 13.0850 - accuracy: 0.3779 - val_loss: 13.6805 - val_accuracy: 0.3095
Epoch 4/10
7/7 [==============================] - 1s 100ms/step - loss: 12.8480 - accuracy: 0.3702 - val_loss: 13.6805 - val_accuracy: 0.3095
Epoch 5/10
7/7 [==============================] - 1s 100ms/step - loss: 13.4008 - accuracy: 0.3650 - val_loss: 13.6805 - val_accuracy: 0.3095
Epoch 6/10
7/7 [==============================] - 1s 99ms/step - loss: 13.0462 - accuracy: 0.3805 - val_loss: 13.6805 - val_accuracy: 0.3095
Epoch 7/10
7/7 [==============================] - 1s 125ms/step - loss: 13.0061 - accuracy: 0.3830 - val_loss: 13.6805 - val_accuracy: 0.3095
Epoch 8/

In [ ]:
WARNING:tensorflow:Model was constructed with shape
 (None, 32, 32, 3) for input KerasTensor(type_spec=TensorSpec(shape=(None, 32, 32, 3), dtype=tf.float32, name='conv2d_input'), name='conv2d_input', 
                description="created by layer 'conv2d_input'"), but it was called on an input with incompatible shape (None, 224, 224, 3).
---------------------------------------------------------------------------

In [ ]:
cnn_model.evaluate(X_test_, y_test_ )

6/6 [==============================] - 0s 14ms/step - loss: 13.6805 - accuracy: 0.3095


[13.680460929870605, 0.3095238208770752]

In [ ]:
cnn_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 30, 30, 8)         224       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 28, 28, 16)        1168      
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 26, 26, 32)        4640      
_________________________________________________________________
flatten (Flatten)            (None, 21632)             0         
_________________________________________________________________
dense (Dense)                (None, 32)                692256    
_________________________________________________________________
dropout (Dropout)            (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 3

In [ ]:
resnet = keras.applications.ResNet50()

102973440/102967424 [==============================] - 1s 0us/step


In [ ]:
resnet.compile(loss='CategoricalCrossentropy',
              optimizer= keras.optimizers.SGD(learning_rate=0.01, momentum=0.9),
              metrics=['accuracy'])

In [ ]:
resnet.summary()

Model: "resnet50"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 224, 224, 3) 0                                            
__________________________________________________________________________________________________
conv1_pad (ZeroPadding2D)       (None, 230, 230, 3)  0           input_1[0][0]                    
__________________________________________________________________________________________________
conv1_conv (Conv2D)             (None, 112, 112, 64) 9472        conv1_pad[0][0]                  
__________________________________________________________________________________________________
conv1_bn (BatchNormalization)   (None, 112, 112, 64) 256         conv1_conv[0][0]                 
___________________________________________________________________________________________

In [ ]:
resnet.fit(X_train_, y_train_, batch_size=64, epochs=10, validation_data=(X_test_, y_test_))

Epoch 1/10
7/7 [==============================] - 303s 42s/step - loss: 3.6363 - accuracy: 0.4936 - val_loss: 1.7882 - val_accuracy: 0.6964
Epoch 2/10
7/7 [==============================] - 289s 41s/step - loss: 0.1918 - accuracy: 0.9460 - val_loss: 6.5078 - val_accuracy: 0.6548
Epoch 3/10
7/7 [==============================] - 301s 43s/step - loss: 0.1899 - accuracy: 0.9434 - val_loss: 4.5564 - val_accuracy: 0.5119
Epoch 4/10
7/7 [==============================] - 290s 41s/step - loss: 0.2829 - accuracy: 0.9460 - val_loss: 1.3787 - val_accuracy: 0.6964
Epoch 5/10
7/7 [==============================] - 287s 41s/step - loss: 0.2543 - accuracy: 0.9229 - val_loss: 4.2636 - val_accuracy: 0.5595
Epoch 6/10
7/7 [==============================] - 284s 40s/step - loss: 0.3890 - accuracy: 0.9049 - val_loss: 20.0862 - val_accuracy: 0.2917
Epoch 7/10
7/7 [==============================] - 286s 41s/step - loss: 0.3068 - accuracy: 0.9229 - val_loss: 63.8487 - val_accuracy: 0.3690
Epoch 8/10
7/7 [==

In [ ]:
resnet.fit(X_train_, y_train_, batch_size=64, epochs=10, validation_data=(X_test_, y_test_))

Epoch 1/10
7/7 [==============================] - 293s 40s/step - loss: 3.7087 - accuracy: 0.4833 - val_loss: 6.1531 - val_accuracy: 0.4940
Epoch 2/10
7/7 [==============================] - 281s 40s/step - loss: 0.1505 - accuracy: 0.9434 - val_loss: 7.3398 - val_accuracy: 0.5119
Epoch 3/10
7/7 [==============================] - 282s 40s/step - loss: 0.0793 - accuracy: 0.9692 - val_loss: 48.8205 - val_accuracy: 0.1964
Epoch 4/10
7/7 [==============================] - 288s 41s/step - loss: 0.1135 - accuracy: 0.9820 - val_loss: 73.0590 - val_accuracy: 0.1964
Epoch 5/10
7/7 [==============================] - 281s 40s/step - loss: 0.1594 - accuracy: 0.9743 - val_loss: 71.5642 - val_accuracy: 0.1964
Epoch 6/10
7/7 [==============================] - 281s 40s/step - loss: 0.1087 - accuracy: 0.9743 - val_loss: 25.4056 - val_accuracy: 0.2083
Epoch 7/10
7/7 [==============================] - 280s 40s/step - loss: 0.3004 - accuracy: 0.8997 - val_loss: 48.1919 - val_accuracy: 0.2440
Epoch 8/10
7/7 